//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastFoodDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommandePayer
    {
        public int Id_Commande { get; set; }
        public string Nom_Serveur { get; set; }
        public string Nom_Table { get; set; }
        public Nullable<System.DateTime> Date_Commande { get; set; }
        public Nullable<decimal> Total_Commande { get; set; }
    }
}
