//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastFoodDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailsCommandeImprimante
    {
        public int Id_DetailCommande { get; set; }
        public int Id_Commande { get; set; }
        public Nullable<int> Id_Imprimante { get; set; }
        public Nullable<int> Id_Produit { get; set; }
        public Nullable<System.DateTime> Date_Produit { get; set; }
        public decimal Quantite { get; set; }
        public Nullable<decimal> Prix { get; set; }
        public string Serveur { get; set; }
        public string Nom_Table { get; set; }
        public Nullable<int> Etat { get; set; }
    
        public virtual Imprimante Imprimante { get; set; }
        public virtual Produit Produit { get; set; }
    }
}
