//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastFoodDemo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GestionEspaceEntities : DbContext
    {
        public GestionEspaceEntities()
            : base("name=GestionEspaceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public virtual DbSet<Categorie> Categorie { get; set; }
        public virtual DbSet<CommandePayer> CommandePayer { get; set; }
        public virtual DbSet<DetailsCommandeImprimante> DetailsCommandeImprimante { get; set; }
        public virtual DbSet<Employer> Employer { get; set; }
        public virtual DbSet<Imprimante> Imprimante { get; set; }
        public virtual DbSet<Produit> Produit { get; set; }
        public virtual DbSet<TableDefault> TableDefault { get; set; }
        public virtual DbSet<Note> Note { get; set; }
        public virtual DbSet<EspaceTable> TablesEspace { get; set; }
    
        public virtual ObjectResult<RapportVentes_Result> RapportVentes(Nullable<System.DateTime> dateDebut, Nullable<System.DateTime> dateFin)
        {
            var dateDebutParameter = dateDebut.HasValue ?
                new ObjectParameter("DateDebut", dateDebut) :
                new ObjectParameter("DateDebut", typeof(System.DateTime));
    
            var dateFinParameter = dateFin.HasValue ?
                new ObjectParameter("DateFin", dateFin) :
                new ObjectParameter("DateFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RapportVentes_Result>("RapportVentes", dateDebutParameter, dateFinParameter);
        }
    
        public virtual ObjectResult<RapportVentesGeneral_Result> RapportVentesGeneral()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RapportVentesGeneral_Result>("RapportVentesGeneral");
        }
    
        public virtual ObjectResult<RapportVentesParEmployer_Result> RapportVentesParEmployer(Nullable<System.DateTime> dateDebut, Nullable<System.DateTime> dateFin, string emloyer)
        {
            var dateDebutParameter = dateDebut.HasValue ?
                new ObjectParameter("DateDebut", dateDebut) :
                new ObjectParameter("DateDebut", typeof(System.DateTime));
    
            var dateFinParameter = dateFin.HasValue ?
                new ObjectParameter("DateFin", dateFin) :
                new ObjectParameter("DateFin", typeof(System.DateTime));
    
            var emloyerParameter = emloyer != null ?
                new ObjectParameter("emloyer", emloyer) :
                new ObjectParameter("emloyer", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RapportVentesParEmployer_Result>("RapportVentesParEmployer", dateDebutParameter, dateFinParameter, emloyerParameter);
        }
    
        public virtual ObjectResult<TotalCommandeParAnnees_Result> TotalCommandeParAnnees()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TotalCommandeParAnnees_Result>("TotalCommandeParAnnees");
        }
    
        public virtual ObjectResult<RapportCommandes_Result> RapportCommandes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RapportCommandes_Result>("RapportCommandes");
        }
    
        public virtual ObjectResult<RapportCommandesParAnnee_Result> RapportCommandesParAnnee()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RapportCommandesParAnnee_Result>("RapportCommandesParAnnee");
        }
    }
}
