//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastFoodDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableDefault
    {
        public string Reference { get; set; }
        public string Nom { get; set; }
        public Nullable<int> Etat { get; set; }
    }
}
